# Generated by Django 6.0.2 on 2026-02-11 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adhar_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='Not Assigned', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='UniversityRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('allotted_date', models.DateField(auto_now_add=True)),
                ('student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Adhar',
        ),
    ]
