# Generated by Django 6.0.1 on 2026-01-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department_query_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
