# Generated by Django 6.0.1 on 2026-01-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='dep',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='emp',
        ),
    ]
