# Generated by Django 6.0.1 on 2026-01-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('document', models.FileField(upload_to='documents')),
                ('audio', models.FileField(upload_to='audio')),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
    ]
